### ISSUE TITLE
replicate your results on food101 dataset

### ISSUE THREAD

**Issue by yinyinl** [gaopengcuhk/Tip-Adapter#2]
Would you consider providing the script to replicate your results on food101 dataset? If someone is to adapt your script on ImageNet, do you have suggestions on what to make sure to adjust?

**Comment by gaopengcuhk** [comment]
We will add scripts for new datasets in a few weeks. Stay tuned.

**Comment by ZrrSkywalker** [comment]
@yinyinl Thanks for your great patience!
We have released our full code base.

**Comment by yinyinl** [comment]
Thank you!
