### ISSUE TITLE
Where is the CLIP-Adapter code, please?

### ISSUE THREAD

**Issue by machengcheng2016** [gaopengcuhk/Tip-Adapter#5]
Greetings! Really fantastic work!
But where is the CLIP-Adapter code? I wonder how is the two-layer MLP in CLIP-Adapter structured.

**Comment by machengcheng2016** [comment]
According to your papers, there is a adapter for language branch in CLIP-Adapter, but there is not in TIP-Adapter. Am I right?

**Comment by ZrrSkywalker** [comment]
Thanks for your interest on our work. The CLIP-Adapter code is partly released at [here](`https://github.com/gaopengcuhk/CLIP-Adapter`), where shows how two-layer MLP structured. We will complete it soon.

**Comment by ZrrSkywalker** [comment]
Thanks for your interest on our work. The CLIP-Adapter code is partly released at here, where shows how two-layer MLP structured. We will complete it soon.

https://github.com/gaopengcuhk/CLIP-Adapter

**Comment by machengcheng2016** [comment]
I see. It seems there is also no adapter for the text branch in [CLIP-Adapter](https://github.com/gaopengcuhk/CLIP-Adapter/blob/main/clip_adapter.py#L102).
Is this because the text adapter is useless compared with the image adapter?
