### ISSUE TITLE
Are CLIP/TIP-Adapter only designed for the few-shot setting?

### ISSUE THREAD

**Issue by machengcheng2016** [gaopengcuhk/Tip-Adapter#6]
Sorry I've got another question.
I did not find experiments under the base-to-new/domain generalization setting and cross-dataset transfer setting, which is conducted by CoCoOp. 
Are CLIP/TIP-Adapter only designed for the few-shot setting? I wonder how the generation abilities are. Maybe you can give me any intuition?

**Comment by ZrrSkywalker** [comment]
It's Okay!
We have conducted base-to-new domain transfer experiments for Tip-Adapter and CLIP-Adapter in the revised paper, which will be on arxiv in a few days.
