### ISSUE TITLE
Details of data augmentation

### ISSUE THREAD

**Issue by SY-Xuan** [gaopengcuhk/Tip-Adapter#7]
In the paper, "the CLIP-style pre-processing resizes the cropped image’s short side to 224 while keeping its original aspect", and you said that you use the CLIP-style RandomResizeCrop.

However, I found that in the code, the standard RandomResizeCrop is used. 

I wonder that is this setting important to the final performance or I misunderstood here?

**Comment by SY-Xuan** [comment]
I think I misunderstood it here. The pre-precessing you mentioned here denotes the pre-precessing at the inference not the training.

**Comment by ZrrSkywalker** [comment]
Yes, the CLIP-style pre-processing inference-time pre-precessing, since CLIP itself is a zero-shot classifier without any downstream training. Different pre-processing would affect 2~3% accuracy to the final performance, so we follow the official ones from CLIP.

**Comment by SY-Xuan** [comment]
Thanks for your kindly replying. I understood.
